language: java

jdk:
  - openjdk8
  # - openjdk9 # Has long become unavailable... So we have to try JDK 10...
  - openjdk10

install:
  - ./gradlew clean jar

env:
  - TEST_FOLDER=ui
  - TEST_FOLDER=service/cart
  - TEST_FOLDER=service/user
  - TEST_FOLDER=repository/order
  - TEST_FOLDER=repository/cart
  - TEST_FOLDER=repository/product
  - TEST_FOLDER=repository/user

script:
  - if [ "${TEST_FOLDER}" = "repository/order" ]; then export COVERAGE=0.3; fi;
  - if [ "${TEST_FOLDER}" = "repository/user" ]; then export COVERAGE=0.3; fi;
  - ./gradlew -p ./monolithic/$TEST_FOLDER check


after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

# "The deploy steps are skipped, if the build is broken."
# https://docs.travis-ci.com/user/job-lifecycle/#deploying-your-code
deploy:
  provider: script
  script: echo "WIP"
