language: java
jdk: openjdk8

install:
  - ./gradlew clean jar


jobs:
  include:
    - stage : test
      name: "Test ui"
      install: skip
      script:
      - ./gradlew -p $TEST_FOLDER check
      env:
      - COVERAGE=0.5
      - TEST_FOLDER=./monolithic/ui
    - stage : test
      name: "Test service/cart"
      install: skip
      script:
      - ./gradlew -p $TEST_FOLDER check
      env:
      - COVERAGE=0.5
      - TEST_FOLDER=./monolithic/service/cart
    - stage : test
      name: "Test service/user"
      install: skip
      script:
      - ./gradlew -p $TEST_FOLDER check
      env:
      - COVERAGE=0.5
      - TEST_FOLDER=./monolithic/service/user
    - stage : test
      name: "Test repository/order"
      install: skip
      script:
      - ./gradlew -p $TEST_FOLDER check
      env:
      - COVERAGE=0.5
      - TEST_FOLDER=./monolithic/repository/order
    - stage : test
      name: "Test repository/cart"
      install: skip
      script:
      - ./gradlew -p $TEST_FOLDER check
      env:
      - COVERAGE=0.5
      - TEST_FOLDER=./monolithic/repository/cart
    - stage : test
      name: "Test repository/product"
      install: skip
      script:
      - ./gradlew -p $TEST_FOLDER check
      env:
      - COVERAGE=0.5
      - TEST_FOLDER=./monolithic/repository/product
    - stage : test
      name: "Test repository/order"
      install: skip
      script:
      - ./gradlew -p $TEST_FOLDER check
      env:
      - COVERAGE=0.3
      - TEST_FOLDER=./monolithic/repository/order

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

# "The deploy steps are skipped, if the build is broken."
# https://docs.travis-ci.com/user/job-lifecycle/#deploying-your-code
deploy:
  - echo "WIP"
