language: java
jdk: openjdk8

install:
  - ./gradlew clean jar

script:
  - ./gradlew test jacocoTestCoverageVerification
  - ./gradlew jacocoTestReport

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

# "The deploy steps are skipped, if the build is broken."
# https://docs.travis-ci.com/user/job-lifecycle/#deploying-your-code
deploy:
  - echo "WIP"
